name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'microsoft'
          cache: 'maven'
      - name: Install graphviz dependency for tests
        run: sudo apt-get install -y graphviz
      - name: "Run tests and package"
        run: "mvn clean package assembly:single"
      - name: "Codecov report"
        run: bash <(curl -s https://codecov.io/bash)
env:
  MAVEN_OPTS: "-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true"
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DO_TOKEN: ${{ secrets.DO_TOKEN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  GH_API_URL: ${{ secrets.GH_API_URL }}