name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install graphviz dependency for tests
        run: sudo apt-get install -y graphviz
      - name: "Run tests and package"
        run: "mvn clean -X package assembly:single"
      - name: "Codecov report"
        run: bash <(curl -s https://codecov.io/bash)
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
